---
title: "Regression Battleship - Final Guess"
author: "Austin Ith"
output: 
  html_document:
    theme: cerulean
    toc: true
    toc_float: true
    code_folding: hide
---

```{r}
library(tidyverse)
library(pander)
# Read in the RBdata here:
rbdata <- read.csv("FinalData.csv", header=TRUE)
```



```{r}
pairs(rbdata, panel = panel.smooth)

lm1 <- lm(Y^2~X5 + X9 + X3 + X4, data = rbdata)
summary(lm1)
pairs(cbind(R=lm1$res, Fit = lm1$fit, rbdata), panel = panel.smooth, col = as.factor(rbdata$X3))

plot(lm1, which =1)

lm2 <- lm(I(Y^2)~X5 + X9 + X3 + X1 + X1:X5 + X1:X9:X5 + X1:X4 + I(X1^3):X4:X5, data = rbdata)
summary(lm2)
pairs(cbind(R=lm2$res, Fit = lm2$fit, rbdata), panel = panel.smooth, col = interaction(rbdata$X3,rbdata$X9))

lm2 <- lm(Y ~ .^2, data = rbdata)
summary(lm2)
pairs(cbind(R=lm2$res, Fit = lm2$fit, rbdata), panel = panel.smooth, col = as.factor(rbdata$X5))

lm2 <- lm(Y^2 ~ X1 + X3 + X5 + X9 + X1:X3 + X1:X5 + X1:X9:X5 + I(X1^4):X4:X5, data = rbdata)
summary(lm2)
pairs(cbind(R=lm2$res, Fit = lm2$fit, rbdata), panel = panel.smooth, col = as.factor(rbdata$X5))


plot(lm2, which =1)

b <- lm2$coefficients

plot(Y^2 ~ X1, data = rbdata)

X3 <- 0
X4 <- 0
X5 <- 0
X9 <- 0
curve(b[1] + b[2]*x + b[3]*X3 + b[6]*x*X3 + b[4]*X5 + b[7]*x*X5 + b[5]*X9 + b[8]*x*X5*X9 + b[9]*x^4*X4*X5, add = T)

X3 <- 0
X4 <- 0
X5 <- 0
X9 <- 1
curve(b[1] + b[2]*x + b[3]*X3 + b[6]*x*X3 + b[4]*X5 + b[7]*x*X5 + b[5]*X9 + b[8]*x*X5*X9 + b[9]*x^4*X4*X5, add = T)

X3 <- 0
X4 <- 0
X5 <- 1
X9 <- 1
curve(b[1] + b[2]*x + b[3]*X3 + b[6]*x*X3 + b[4]*X5 + b[7]*x*X5 + b[5]*X9 + b[8]*x*X5*X9 + b[9]*x^4*X4*X5, add = T)

X3 <- 0
X4 <- 1
X5 <- 1
X9 <- 1
curve(b[1] + b[2]*x + b[3]*X3 + b[6]*x*X3 + b[4]*X5 + b[7]*x*X5 + b[5]*X9 + b[8]*x*X5*X9 + b[9]*x^4*X4*X5, add = T)

X3 <- 1
X4 <- 1
X5 <- 1
X9 <- 1
curve(b[1] + b[2]*x + b[3]*X3 + b[6]*x*X3 + b[4]*X5 + b[7]*x*X5 + b[5]*X9 + b[8]*x*X5*X9 + b[9]*x^4*X4*X5, add = T)

X3 <- 1
X4 <- 0
X5 <- 0
X9 <- 0
curve(b[1] + b[2]*x + b[3]*X3 + b[6]*x*X3 + b[4]*X5 + b[7]*x*X5 + b[5]*X9 + b[8]*x*X5*X9 + b[9]*x^4*X4*X5, add = T)

X3 <- 1
X4 <- 1
X5 <- 0
X9 <- 0
curve(b[1] + b[2]*x + b[3]*X3 + b[6]*x*X3 + b[4]*X5 + b[7]*x*X5 + b[5]*X9 + b[8]*x*X5*X9 + b[9]*x^4*X4*X5, add = T)

X3 <- 1
X4 <- 1
X5 <- 1
X9 <- 0
curve(b[1] + b[2]*x + b[3]*X3 + b[6]*x*X3 + b[4]*X5 + b[7]*x*X5 + b[5]*X9 + b[8]*x*X5*X9 + b[9]*x^4*X4*X5, add = T)

X3 <- 0
X4 <- 1
X5 <- 0
X9 <- 0
curve(b[1] + b[2]*x + b[3]*X3 + b[6]*x*X3 + b[4]*X5 + b[7]*x*X5 + b[5]*X9 + b[8]*x*X5*X9 + b[9]*x^4*X4*X5, add = T)

X3 <- 0
X4 <- 1
X5 <- 1
X9 <- 0
curve(b[1] + b[2]*x + b[3]*X3 + b[6]*x*X3 + b[4]*X5 + b[7]*x*X5 + b[5]*X9 + b[8]*x*X5*X9 + b[9]*x^4*X4*X5, add = T)

X3 <- 0
X4 <- 0
X5 <- 1
X9 <- 0
curve(b[1] + b[2]*x + b[3]*X3 + b[6]*x*X3 + b[4]*X5 + b[7]*x*X5 + b[5]*X9 + b[8]*x*X5*X9 + b[9]*x^4*X4*X5, add = T)

X3 <- 1
X4 <- 0
X5 <- 1
X9 <- 0
curve(b[1] + b[2]*x + b[3]*X3 + b[6]*x*X3 + b[4]*X5 + b[7]*x*X5 + b[5]*X9 + b[8]*x*X5*X9 + b[9]*x^4*X4*X5, add = T)

X3 <- 0
X4 <- 1
X5 <- 0
X9 <- 1
curve(b[1] + b[2]*x + b[3]*X3 + b[6]*x*X3 + b[4]*X5 + b[7]*x*X5 + b[5]*X9 + b[8]*x*X5*X9 + b[9]*x^4*X4*X5, add = T)

X3 <- 1
X4 <- 0
X5 <- 0
X9 <- 1
curve(b[1] + b[2]*x + b[3]*X3 + b[6]*x*X3 + b[4]*X5 + b[7]*x*X5 + b[5]*X9 + b[8]*x*X5*X9 + b[9]*x^4*X4*X5, add = T)

X3 <- 1
X4 <- 1
X5 <- 0
X9 <- 1
curve(b[1] + b[2]*x + b[3]*X3 + b[6]*x*X3 + b[4]*X5 + b[7]*x*X5 + b[5]*X9 + b[8]*x*X5*X9 + b[9]*x^4*X4*X5, add = T)

X3 <- 1
X4 <- 0
X5 <- 1
X9 <- 1
curve(b[1] + b[2]*x + b[3]*X3 + b[6]*x*X3 + b[4]*X5 + b[7]*x*X5 + b[5]*X9 + b[8]*x*X5*X9 + b[9]*x^4*X4*X5, add = T)





```












## The Model of your Guess

<!-- Enter your guessed model in the math notation below. -->

$$
  Y_i = \beta_0 + ...YourGuess... + \epsilon_i
$$

## The lm(...) of your Guess

<!-- Provide your estimates of each model coefficient along with the Adjusted R-squared of your model:-->

```{r}
## Input your lm(Y ~ ... ,data=rbdata)
final.lm <- lm(Y ~ X6 + X9, data=rbdata) #replace the "1" with your model
```

```{r}
###################################################################
#Don't edit this part:
pander(summary(final.lm)$coefficients)
```

**Adjusted R-squared**: `r summary(final.lm)$adj.r.squared`


## The Plot of your Guess

```{r}
# Draw a picture of your guess at the model here:
# Remember, your guess only counts for credit if you plot it.

```






 

 

 

 