---
title: "Regression Battleship - Final Guess"
author: "Austin Ith"
output: 
  html_document:
    theme: cerulean
    toc: true
    toc_float: true
    code_folding: hide
---

```{r}
library(tidyverse)
library(pander)
# Read in the RBdata here:
rbdata <- read.csv("Kovalyov-RBdata.csv", header=TRUE)
```

.86(R-SQUARED)
3 variables

```{r}
pairs(rbdata, panel = panel.smooth)

lm1 <- lm(Y~X4, data = rbdata)
summary(lm1)
pairs(cbind(R=lm1$res, Fit = lm1$fit, rbdata), panel = panel.smooth, col = as.factor(X10))

lm2 <- lm(Y~ X4 + I(X4^2) + I(X4^3) + X10, data = rbdata)
summary(lm2)
pairs(cbind(R=lm2$res, Fit = lm2$fit, rbdata), panel = panel.smooth, col = as.factor(rbdata$X10))

lm3 <- lm(Y ~ X2* X4 *X7, data = rbdata)
summary(lm3)
pairs(cbind(R=lm3$res, Fit = lm3$fit, rbdata), panel = panel.smooth)

# Drop X4:X7

lm4 <- lm(Y ~ X2 + X4 + X7 + X2:X4 +X2:X7 + X2:X4:X7, data = rbdata)
summary(lm4)
pairs(cbind(R=lm4$res, Fit = lm4$fit, rbdata), panel = panel.smooth)

# Add X10

lm4 <- lm(Y ~ X2 + X4 + X7 + X2:X4 +X2:X7 + X2:X4:X7 + X10, data = rbdata)
summary(lm4)
pairs(cbind(rbdata, X2.4 = (rbdata$X7/rbdata$X2)), panel = panel.smooth, col = as.factor(rbdata$X10))

# Start Over 

pairs(rbdata, panel = panel.smooth, col = interaction(rbdata$X10, rbdata$X7))
pairs(cbind(rbdata, X2.4 = (rbdata$X4/rbdata$X2)), panel = panel.smooth, col = as.factor(rbdata$X5))








plot(lm3, which = 1)
# Y~.^2
plot(Y ~ X2, data=rbdata, col=interaction(X4,X7,X10), pch=16)

b <- lm3$coefficients


plot(Y~X3, rbdata)
X5 = 0
X6 = 0
X8 = 0
X9 = 0
curve(b[1] + b[2]*x + b[3]*X5 + b[5]*X5*x + b[6]*X5*x^2 + b[4]*X6 + b[8]*X8*x + b[7]*X8*x + b[9]*X5*X8, add = T)
X5 = 1
X6 = 0
X8 = 0
X9 = 0
curve(b[1] + b[2]*x + b[3]*X5 + b[5]*X5*x + b[6]*X5*x^2 + b[4]*X6 + b[8]*X8*x + b[7]*X8*x + b[9]*X5*X8, add = T)
X5 = 0
X6 = 1
X8 = 0
X9 = 0
curve(b[1] + b[2]*x + b[3]*X5 + b[5]*X5*x + b[6]*X5*x^2 + b[4]*X6 + b[8]*X8*x + b[7]*X8*x + b[9]*X5*X8, add = T)
X5 = 1
X6 = 0
X8 = 1
X9 = 0
curve(b[1] + b[2]*x + b[3]*X5 + b[5]*X5*x + b[6]*X5*x^2 + b[4]*X6 + b[8]*X8*x + b[7]*X8*x + b[9]*X5*X8, add = T)





```












## The Model of your Guess

<!-- Enter your guessed model in the math notation below. -->

$$
  Y_i = \beta_0 + ...YourGuess... + \epsilon_i
$$

## The lm(...) of your Guess

<!-- Provide your estimates of each model coefficient along with the Adjusted R-squared of your model:-->

```{r}
## Input your lm(Y ~ ... ,data=rbdata)
final.lm <- lm(Y ~ X6 + X9, data=rbdata) #replace the "1" with your model
```

```{r}
###################################################################
#Don't edit this part:
pander(summary(final.lm)$coefficients)
```

**Adjusted R-squared**: `r summary(final.lm)$adj.r.squared`


## The Plot of your Guess

```{r}
# Draw a picture of your guess at the model here:
# Remember, your guess only counts for credit if you plot it.

```






 

 

 

 